// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAtPMyoQhAcGK_3ICoYUYrDmlT_R9r_Ts',
    appId: '1:671163813815:web:57abc1c21f6414b0a26232',
    messagingSenderId: '671163813815',
    projectId: 'fcmpractice-510ca',
    authDomain: 'fcmpractice-510ca.firebaseapp.com',
    storageBucket: 'fcmpractice-510ca.appspot.com',
    measurementId: 'G-G9LRZ1TTQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTPP9Spcv6VsOHrB_gOpuDf9z-QqIS3nc',
    appId: '1:671163813815:android:1dd24d19b0701762a26232',
    messagingSenderId: '671163813815',
    projectId: 'fcmpractice-510ca',
    storageBucket: 'fcmpractice-510ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLlEjMltHEcEAQQcioyUE-rsUuqOcffU',
    appId: '1:671163813815:ios:2c1091772eda3c23a26232',
    messagingSenderId: '671163813815',
    projectId: 'fcmpractice-510ca',
    storageBucket: 'fcmpractice-510ca.appspot.com',
    iosClientId: '671163813815-8e5ar3gq7v1ajhsoruv0735drc0m1pof.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLlEjMltHEcEAQQcioyUE-rsUuqOcffU',
    appId: '1:671163813815:ios:2c1091772eda3c23a26232',
    messagingSenderId: '671163813815',
    projectId: 'fcmpractice-510ca',
    storageBucket: 'fcmpractice-510ca.appspot.com',
    iosClientId: '671163813815-8e5ar3gq7v1ajhsoruv0735drc0m1pof.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmPractice',
  );
}
